# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pantalaimon = {
    pname = "pantalaimon";
    version = "a15f3e49c3672741f16ded2eccab55297ccd43c4";
    src = fetchFromGitHub {
      owner = "matrix-org";
      repo = "pantalaimon";
      rev = "a15f3e49c3672741f16ded2eccab55297ccd43c4";
      fetchSubmodules = false;
      sha256 = "sha256-wQFK0o8W1K0QaKz3fqPn3YC2Fg6/+gNXh2AMepbhQm8=";
    };
    date = "2024-11-01";
  };
}
